spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://34.69.243.2:5432/postgres
    username: postgres
    password: petz

security:
  oauth2:
    client:
      scope: password
      client-id: petz-client
      client-secret: 123
